### PR TITLE
improve bundling, demo and hover rendering

### PR DESCRIPTION
**Pull request by acao**
- finish the reorg @imolorhe started - consistent file names, move features to features directory
- switch to `nodeResolution: bundler` for esm, get rid of .js imports but still something newer than `Node`. keep `nodeResolution: Node` for cjs
- fix some issues with hover rendering, add hover rendering of `$ref` pointers! (see image)
- demo improvements - persist the edited values, use shema cache, remember the chosen schema, and change the headers based on the chosen schema (going to improve this further)
image

### CODE REVIEW

**Review by imolorhe — COMMENTED** [review]
Are we sure changing the module resolution wouldn't reintroduce issues? I see that we are removing the ".je" suffix which was added when fixing a reported issue with resolving the module

**Comment by acao** [comment]
@imolorhe great point - I looked up the source  to cm6-buildhelper and they also use `moduleResolution: node` so let's keep it matching

**Comment by acao** [comment]
@imolorhe this means disabling top level await, which also means we must instantiate the shiki renderer with an async iife :/

**Comment by acao** [comment]
forgot changeset for this 😆

**Pull request merged**
