### PR TITLE
fix #105 - validate all strings

### LINKED ISSUE #105: When the schema has required fields, unexpanded {} will not trigger validation, expanded {} can trigger validation
image

image

my use schema:
```json
{
    "type": "object",
    "properties": {
        "opsProjectID": {
            "type": "string",
            "description": "项目id",
            "x-go-field-name": "OpsProjectID",
            "x-tag-json": "opsProjectID"
        },
        "packageVersionID": {
            "type": "string",
            "description": "部署包版本id",
            "x-go-field-name": "PackageVersionID",
            "x-tag-json": "packageVersionID"
        },
        "remark": {
            "type": "string",
            "description": "发布描述",
            "x-go-field-name": "Remark",
            "x-tag-json": "remark"
        },
        "envs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "agentID": {
                        "type": "string",
                        "description": "集群",
                        "x-go-field-name": "AgentID",
                        "x-tag-json": "agentID"
                    },
                    "copyAgentIDs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "需要copy的集群集合\n\nApplicationTemplateInstanceSet []*ApplicationRelateTemplateAndInstance `json:\"applicationTemplateInstance,omitempty\"` // 服务模版实例关联",
                        "x-go-field-name": "CopyAgentIDs",
                        "x-tag-json": "copyAgentIDs,omitempty"
                    },
                    "namespace": {
                        "type": "string",
                        "description": "命名空间",
                        "x-go-field-name": "Namespace",
                        "x-tag-json": "namespace"
                    }
                },
                "required": [
                    "agentID",
                    "namespace"
                ],
                "x-id": "ApplyEnvRequest"
            },
            "description": "环境集合",
            "x-go-field-name": "Envs",
            "x-tag-json": "envs"
        }
    },
    "required": [
        "opsProjectID",
        "packageVersionID",
        "remark",
        "envs"
    ],
    "x-id": "CreateApplyParams",
    "x-go-field-name": "Body"
}
```

associate #99, this bug has not been resolved, unable to reopen bug

when the schema has required fields, expect that both unexpanded or expanded {} can trigger verification

### PR DESCRIPTION
**Pull request by acao**
any string that is not empty, including whitespace strings, should validate?

### CODE REVIEW

**Review by rookie-luochao — COMMENTED** [review]
This change does not seem to completely fix the validation problem

**Comment by imolorhe** [comment]
@rookie-luochao how did you verify that?

**Comment by imolorhe** [comment]
@rookie-luochao what version are you using?

**Comment by rookie-luochao** [comment]
> @rookie-luochao what version are you using?

0.7.6

**Pull request merged**
