### PR TITLE
chore: Move non runtime packages to dev dependencies

### PR DESCRIPTION
**Pull request by NickTomlin**
I noticed these packages were bringing in some extra dependencies of their own but seem unused except for internal development.

### CODE REVIEW

**Review by imolorhe — APPROVED** [review]

**Review by imolorhe — CHANGES_REQUESTED** [review]
Looks like the lock file isn't updated. Deploys are failing

**Comment by NickTomlin** [comment]
Ah, sorry. I'm unfamiliar with `pnpm` I've gone ahead and run 

```
npx pnpm@8.6.6 install
```

And it looks like that has updated the lockfile.

I didn't see a [`CONTRIBUTING.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file or dev instructions in the README. 

I'd be happy to open a PR with a file like that with some basic how-to's if that would be helpful. Off the top of my head I can think about:

- Development setup (using `pnpm`)
- Tests (adding tests, running tests locally, etc)
- How to use changeset to describe PR

**Comment by acao** [comment]
thanks for this, Nick! you're one of our first outside contributors,  sorry for that oversight, but either way I'll be sure to add a contributing.md moving forward!

looks like the install worked by the way! just one failing test now, I will check back later when i get home

**Comment by NickTomlin** [comment]
👍 np! Thank you for the quick response

**Pull request merged**
